"""Constants for the Ryanair integration."""

DOMAIN = "ryanair"
CONF_DEVICE_FINGERPRINT = "X-DEVICE-FINGERPRINT"
MFA_TOKEN = "mfaToken"
MFA_CODE = "mfaCode"
CUSTOMER_ID = "customerId"
TOKEN = "token"
HOST = "https://services-api.ryanair.com/usrprof/v2/"
ACCOUNT_LOGIN = "accountLogin"
DEVICE_VERIFICATION = "deviceFingerprint"
ACCOUNT_VERIFICATION = "accountVerifications"
RESEND = "resend"
CONF_POLICY_AGREED = "policyAgreed"

CODE_PASSWORD_WRONG = "Password.Wrong"
CODE_MFA_CODE_WRONG = "Mfa.Wrong.Code"
CODE_TRIES_REMAINING = "Account.Password.TryCount.Remaining"
CODE_UNKNOWN_DEVICE = "Account.UnknownDeviceFingerprint"
CODE_MFA_TOKEN = "Mfa.Token"
